### Create User by register
POST /auth/register
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded

name=bildan&email=bildan@mail2.com&password=1234

### Get All Users
GET /users
Host: localhost:8080

### Get User Detail
GET /users/2
Host: localhost:8080

### Delete User
DELETE /users/5
Host: localhost:8080

### Edit User
PUT /users/4
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded

name=bildanjauhary&email=bildan@mail.com&password=1234
