### Create User by register
POST /auth/register
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded

name=test90s1&email=1sdgnsdg@mail.com&password=1234

### Get All Users
GET /users?page=1
Host: localhost:8080

### Get User Detail
GET /users/1
Host: localhost:8080

### Delete User
DELETE /users/5
Host: localhost:8080

### Edit User
PUT /users/1
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded

name=test&email=bildan@mail.com&password=1234
